"""Create tables

Revision ID: 7b86d7397ead
Revises: efc19b449135
Create Date: 2025-07-17 21:18:24.624742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b86d7397ead'
down_revision = 'efc19b449135'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###